In [52]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [77]:
import pandas as pd
import numpy as np

In [78]:
filename = '/content/drive/Othercomputers/My Laptop/data-science-assignments/02 - Manipulating Data/RailsToTrails_National Count Data_week.xlsx'

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timeframe                   52 non-null     object
 1   Week of                     52 non-null     datetime64[ns]
 2    2019 counts (31 counters)  52 non-null     int64
 3    2020 counts (31 counters)  52 non-null     int64
 4   2021 Counts                 0 non-null      float64
 5   Change 2019-2020            52 non-null     float64
 6   Unnamed: 6                  52 non-null     float64
 7   Unnamed: 7                  0 non-null      float64
 8   Unnamed: 8                  1 non-null      float64
 9   Unnamed: 9                  1 non-null      float64
dtypes: datetime64[ns](1), float64(6), int64(2), object(1)
memory usage: 4.2+ KB

In [81]:
df.drop(['Unnamed: 7','Unnamed: 8','Unnamed: 9'],1,inplace=True)

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timeframe                   52 non-null     object
 1   Week of                     52 non-null     datetime64[ns]
 2    2019 counts (31 counters)  52 non-null     int64
 3    2020 counts (31 counters)  52 non-null     int64
 4   2021 Counts                 0 non-null      float64
 5   Change 2019-2020            52 non-null     float64
 6   Unnamed: 6                  52 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(1)
memory usage: 3.0+ KB

#The number of missing values is 206

In [83]:
df.rename(columns={'Unnamed: 6':'percent_change'},inplace=True)

In [84]:
df['2021 Counts'] = df['2021 Counts'].fillna(0)

In [85]:
df.rename(columns={' 2019 counts (31 counters)':'counts_2019',' 2020 counts (31 counters)':'counts_2020','2021 Counts':'counts_2021'},inplace=True)

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Timeframe         52 non-null     object
 1   Week of           52 non-null     datetime64[ns]
 2   counts_2019       52 non-null     int64
 3   counts_2020       52 non-null     int64
 4   counts_2021       52 non-null     float64
 5   Change 2019-2020  52 non-null     float64
 6   percent_change    52 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(1)
memory usage: 3.0+ KB